version: '3.7'

services:
  mongo:
    image: 'mongo:4.2'
    env_file: .env
    environment:
      - MONGO_URI=$MONGO_URI

    ports:
      - '27017:27017'

  web:
    build: '.'
    ports:
      - '3000:3000'
    depends_on:
      - 'mongo'
